import type { ColumnType, Generated } from "kysely";

// ---------------------------------------------------------------------------
// Helper aliases
// ---------------------------------------------------------------------------

/** Column auto-generated by the database (SERIAL / DEFAULT NOW()). */
type Timestamp = ColumnType<Date, Date | string | undefined, Date | string>;

/** Column that is set on insert but never updated. */
type CreatedAt = ColumnType<Date, Date | string | undefined, never>;

/** JSONB column – accepts any JSON-serialisable value. */
type JsonValue = ColumnType<unknown, unknown, unknown>;

// ---------------------------------------------------------------------------
// Table interfaces
// ---------------------------------------------------------------------------

export interface LambdaFunctionTable {
  id: Generated<bigint>;
  function_arn: string;
  function_name: string;
  description: string | null;
  memory_mb: Generated<number>;
  timeout_seconds: Generated<number>;
  estimated_duration_ms: Generated<number>;
  custom_base_fee: bigint | null;
  enabled: Generated<boolean>;
  created_at: Timestamp;
  updated_at: Timestamp;

  // 002 – function specs
  input_schema: JsonValue | null;
  output_schema: JsonValue | null;
  examples: Generated<JsonValue>;
  tags: Generated<string[]>;
  version: Generated<string>;
  author: string | null;
  documentation_url: string | null;

  // 009 – resolved IP
  resolved_ip: string | null;

  // 010 – private registry / ownership
  owner_address: string | null;
  visibility: Generated<string>; // 'public' | 'private'
  marketplace_fee_bps: number | null;

  // 022 – endpoint auth & metadata
  endpoint_auth_encrypted: string | null;
  auth_type: string | null; // 'bearer' | 'api_key' | 'basic' | 'custom_header'
  open_api_spec_url: string | null;
  pay_to_address: string | null;
  pricing_model: Generated<string>; // 'fixed' | 'metered'

  // 024 – full-text search (managed by trigger, read-only)
  search_vector: ColumnType<unknown, unknown | undefined, unknown | undefined>;

  // 026 – GPU compute
  gpu_type: string | null; // 'nvidia-t4' | 'nvidia-a10g' | 'nvidia-a100'
  gpu_memory_mb: number | null;
}

export interface LambdaInvocationTable {
  id: Generated<bigint>;
  function_name: string;
  payer_address: string;
  amount_paid: bigint;
  tx_hash: string | null;
  status_code: number;
  success: boolean;
  duration_ms: Generated<bigint>;
  created_at: CreatedAt;

  // 003 – billing detail columns
  actual_cloud_cost: bigint | null;
  fee_amount: bigint | null;
  refund_amount: bigint | null;
  refund_status: string | null;
  refund_tx_hash: string | null;
  billed_duration_ms: bigint | null;
  memory_mb: number | null;
}

export interface PricingConfigTable {
  id: Generated<bigint>;
  base_fee: bigint;
  memory_rate_per_128mb: bigint;
  duration_rate_per_100ms: bigint;
  network: Generated<string>;
  updated_at: Timestamp;
}

export interface PricingConfigAuditTable {
  id: Generated<bigint>;
  pricing_config_id: bigint;
  operation: string; // 'INSERT' | 'UPDATE' | 'DELETE'
  old_base_fee: bigint | null;
  old_memory_rate: bigint | null;
  old_duration_rate: bigint | null;
  new_base_fee: bigint | null;
  new_memory_rate: bigint | null;
  new_duration_rate: bigint | null;
  changed_by: string | null;
  change_reason: string | null;
  changed_at: Timestamp;
}

export interface CreditTable {
  id: Generated<bigint>;
  payer_address: string;
  amount: bigint;
  reason: string; // 'failed_refund' | 'below_threshold' | 'manual'
  source_tx_hash: string | null;
  source_invocation_id: bigint | null;
  redeemed: Generated<boolean>;
  redeemed_at: Date | null;
  redeemed_tx_hash: string | null;
  created_at: CreatedAt;

  // 032 – explicit withdrawal status
  withdrawal_status: Generated<string>; // 'available' | 'pending' | 'withdrawn'
}

export interface RefundTable {
  id: Generated<bigint>;
  payer_address: string;
  amount: bigint;
  status: string; // 'pending' | 'success' | 'failed' | 'credited'
  source_tx_hash: string | null;
  source_invocation_id: bigint | null;
  refund_tx_hash: string | null;
  error_message: string | null;
  gas_used: bigint | null;
  created_at: CreatedAt;
  completed_at: Date | null;
}

export interface VoucherRedemptionTable {
  id: Generated<bigint>;
  voucher_id: string;
  source: string;
  payer_address: string;
  amount: bigint;
  issued_at: Date | string;
  expires_at: Date | string;
  redeemed_at: Timestamp | null;
  refund_tx_hash: string | null;
  status: Generated<string>; // 'issued' | 'pending' | 'success' | 'failed'
}

export interface PaymentNonceTable {
  id: Generated<bigint>;
  nonce: string;
  payer_address: string;
  amount: bigint;
  resource: string;
  tx_hash: string | null;
  status: Generated<string>; // 'pending' | 'settled' | 'failed'
  created_at: Timestamp;
  expires_at: Date | string;
}

export interface AuthNonceTable {
  id: Generated<bigint>;
  signer_address: string;
  nonce: string;
  created_at: CreatedAt;
  expires_at: Date | string;
}

export interface FunctionAccessListTable {
  id: Generated<bigint>;
  function_name: string;
  invoker_address: string;
  granted_by: string;
  created_at: CreatedAt;
}

export interface EarningTable {
  id: Generated<bigint>;
  owner_address: string;
  function_name: string;
  amount: bigint;
  invocation_id: bigint | null;
  source_tx_hash: string | null;
  withdrawn: Generated<boolean>;
  withdrawn_at: Date | null;
  withdrawn_tx_hash: string | null;
  created_at: CreatedAt;

  // 032 – explicit withdrawal status
  withdrawal_status: Generated<string>; // 'available' | 'pending' | 'withdrawn'
}

export interface LeaseResourceTable {
  id: string; // e.g. "t3-medium" (user-supplied PK)
  display_name: string;
  instance_type: string;
  vcpus: number;
  memory_gb: number;
  storage_gb: Generated<number>;
  ami_id: string;
  ssh_user: Generated<string>;
  description: string | null;
  price_1d: bigint;
  price_7d: bigint;
  price_30d: bigint;
  max_concurrent: Generated<number>;
  enabled: Generated<boolean>;
  created_at: Timestamp;
  updated_at: Timestamp;

  // 012 – pricing overhaul
  margin_percent: Generated<number>;
  default_storage_gb: Generated<number>;
  min_storage_gb: Generated<number>;
  max_storage_gb: Generated<number>;
  egress_limit_gb: Generated<number>;
  ingress_limit_gb: Generated<number>;
  public_ip_default: Generated<boolean>;
}

export interface LeaseTable {
  id: string; // UUID (user-supplied PK)
  resource_id: string;
  payer_address: string;
  amount_paid: bigint;
  payment_tx_hash: string;
  duration_days: number; // 1 | 7 | 30
  instance_id: string | null;
  public_ip: string | null;
  ssh_public_key: string;
  encrypted_private_key: string;
  user_public_key: string;
  encryption_nonce: string;
  status: Generated<string>; // 'pending' | 'provisioning' | 'running' | 'terminated' | 'failed'
  status_message: string | null;
  error_message: string | null;
  provision_attempts: Generated<number>;
  created_at: Timestamp;
  provisioned_at: Date | null;
  expires_at: Date | string;
  terminated_at: Date | null;

  // 012 – pricing overhaul add-ons
  storage_gb: number | null;
  has_public_ip: Generated<boolean>;
  has_load_balancer: Generated<boolean>;
  egress_limit_gb: number | null;
  ingress_limit_gb: number | null;
  egress_used_gb: Generated<number>;
  ingress_used_gb: Generated<number>;
  bandwidth_checked_at: Date | null;
  price_breakdown: JsonValue | null;

  // 018 – security groups
  security_group_id: string | null;

  // 020 – admin/GDPR
  terminated_reason: string | null;
  anonymized_at: Date | null;
}

export interface AwsPricingTable {
  id: Generated<number>;
  service: string; // 'ec2' | 'ebs' | 'ipv4' | 'data_transfer' | 'alb'
  resource_key: string;
  region: string;
  unit: string; // 'per_hour' | 'per_gb_month' | 'per_gb'
  price_usd: number;
  last_fetched_at: Timestamp;
  created_at: Timestamp;
}

export interface AdminAuditLogTable {
  id: Generated<bigint>;
  admin_ip: string;
  action: string;
  target_type: string; // 'lease' | 'resource' | 'function'
  target_id: string;
  details: JsonValue | null;
  created_at: CreatedAt;
}

export interface StorageSessionTable {
  id: Generated<string>;
  payer_address: string;
  bucket: string;
  prefix: string;
  max_size_bytes: Generated<bigint>;
  used_bytes: Generated<bigint>;
  expires_at: Date | string;
  created_at: CreatedAt;
  tx_hash: string;
}

export interface BatchInvocationTable {
  id: Generated<string>;
  function_name: string;
  payer_address: string;
  tx_hash: string;
  total_items: number;
  completed_items: Generated<number>;
  failed_items: Generated<number>;
  status: Generated<string>; // 'running' | 'completed' | 'partial_failure'
  amount_paid: bigint;
  actual_cloud_cost: bigint | null;
  fee_amount: bigint | null;
  refund_amount: bigint | null;
  refund_status: string | null;
  refund_tx_hash: string | null;
  created_at: CreatedAt;
  completed_at: Date | null;
}

export interface AsyncJobTable {
  id: Generated<string>;
  function_name: string;
  payer_address: string;
  tx_hash: string;
  status: Generated<string>; // 'pending' | 'running' | 'completed' | 'failed'
  input: JsonValue;
  result: JsonValue | null;
  error_message: string | null;
  amount_paid: bigint;
  actual_cost: bigint | null;
  created_at: CreatedAt;
  started_at: Date | null;
  completed_at: Date | null;
  expires_at: Date | string;
  storage_session_id: string | null;
}

export interface BudgetTable {
  id: Generated<string>;
  payer_address: string;
  tx_hash: string;
  total_amount: bigint;
  remaining_amount: bigint;
  status: Generated<string>; // 'active' | 'exhausted' | 'expired' | 'revoked'
  expires_at: Date | string;
  allowed_functions: string[] | null;
  max_per_invocation: bigint | null;
  created_at: CreatedAt;
  updated_at: Timestamp;
}

export interface BudgetTransactionTable {
  id: Generated<bigint>;
  budget_id: string;
  function_name: string;
  amount: bigint;
  invocation_id: bigint | null;
  created_at: CreatedAt;
}

export interface PipelineExecutionTable {
  id: Generated<string>;
  payer_address: string;
  tx_hash: string;
  status: Generated<string>; // 'running' | 'completed' | 'failed'
  steps: JsonValue;
  current_step: Generated<number>;
  step_results: Generated<JsonValue>;
  amount_paid: bigint;
  actual_cost: Generated<bigint>;
  error_message: string | null;
  created_at: CreatedAt;
  completed_at: Date | null;
}

export interface OwnershipTransferRequestTable {
  id: Generated<bigint>;
  function_name: string;
  current_owner: string;
  new_owner: string;
  status: Generated<string>; // 'pending' | 'accepted' | 'cancelled' | 'expired'
  expires_at: Date | string;
  created_at: CreatedAt;
  updated_at: Timestamp;
}

// ---------------------------------------------------------------------------
// Database interface (all tables)
// ---------------------------------------------------------------------------

export interface Database {
  lambda_functions: LambdaFunctionTable;
  lambda_invocations: LambdaInvocationTable;
  pricing_config: PricingConfigTable;
  pricing_config_audit: PricingConfigAuditTable;
  credits: CreditTable;
  refunds: RefundTable;
  voucher_redemptions: VoucherRedemptionTable;
  payment_nonces: PaymentNonceTable;
  auth_nonces: AuthNonceTable;
  function_access_list: FunctionAccessListTable;
  earnings: EarningTable;
  lease_resources: LeaseResourceTable;
  leases: LeaseTable;
  aws_pricing: AwsPricingTable;
  admin_audit_log: AdminAuditLogTable;
  storage_sessions: StorageSessionTable;
  batch_invocations: BatchInvocationTable;
  async_jobs: AsyncJobTable;
  budgets: BudgetTable;
  budget_transactions: BudgetTransactionTable;
  pipeline_executions: PipelineExecutionTable;
  ownership_transfer_requests: OwnershipTransferRequestTable;
}
